import RNAQuasiPowers.Radicand
import RNAQuasiPowers.GeneratingFunction
import RNAQuasiPowers.GoldenRoot
import RNAQuasiPowers.Covariance
import RNAQuasiPowers.ImplicitDerivatives
import RNAQuasiPowers.AlgebraicCertificate
