name = "wow_145"
version = "0.1.0"
defaultTargets = ["WOW145"]

[[require]]
name = "wow_146"
git = "https://github.com/akakabrian/WOW-146.git"
rev = "0b750ac1ac987d7085fff796b4ea91a0cf4ecd70"

[[lean_lib]]
name = "WOW145"
