/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import QuantumGraphSemantic

/-!
# Exhaustive finite data for the 47 odd-perfect-matching support orbits

The arrays are generated by `generate_orbit_data.py`. Permutations are ordered
lexicographically and act from the new vertex labels to the old vertex labels.
-/

namespace QuantumGraphOrbitData

def parseRow (line : String) : Array Nat :=
  (line.splitOn ",").toArray.map String.toNat!

def parseTable (contents : String) : Array (Array Nat) :=
  (contents.splitOn "\n").toArray.map parseRow

def permutationTable : Array (Array Nat) :=
  parseTable (include_str "orbit_data" / "permutations.txt")

def inversePermutationTable : Array (Array Nat) :=
  parseTable (include_str "orbit_data" / "inverse_permutations.txt")

def edgeActionTable : Array (Array Nat) :=
  parseTable (include_str "orbit_data" / "edge_actions.txt")

def matchingActionTable : Array (Array Nat) :=
  parseTable (include_str "orbit_data" / "matching_actions.txt")

def representativeTable : Array Nat :=
  parseRow (include_str "orbit_data" / "representatives.txt")

/-- Encodes `case * 720 + permutation` for each of the 32768 labelled masks,
split into 256 rows of 128 entries to keep elaboration shallow. -/
def classificationTable : Array (Array Nat) :=
  parseTable (include_str "orbit_data" / "classification.txt")

end QuantumGraphOrbitData
